# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d540712ccab29a79904fa44211e4d363403fc13507166ef7d1cc7f364d38faa53b6ab07ff65ad031eacbd34b697e8f620f132f9cb87648ada7665fe04acb8529

test:
  secret_key_base: 0417c09940bc362c49136a7ad2eef95a64eb4033f7c665dee841157bb5e7cd259f60f6f9b6dab2a650e3fd5a14f028e297ece8e8463bcced5f069b1e20a298de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
